import type { Metadata } from "next";
import { figtree } from "@/fonts/fonts";
import "../styles/globals.css";
import PromotionalBanner from "@/components/layout/PromotionalBanner";
import Header from "@/components/layout/Header";


export const metadata: Metadata = {
  title: "Fametonic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figtree.className}>
      <body className={`antialiased scrollbar`}>
        <PromotionalBanner/>
        <Header/>
        {children}
      </body>
    </html>
  );
}
