import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import { Dosis } from "next/font/google";
import "../styles/globals.css";
import OfferTopBanner from "@/components/layout/OfferTopBanner";

const figtree = Figtree({
  subsets: ['latin'],
})
const dosis = Dosis({
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Fametonic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figtree.className}>
      <body className={`antialiased`}>
        <OfferTopBanner/>
        {children}
      </body>
    </html>
  );
}
